

name: Archive and Zip

on:
  push:
    branches:
      - main

jobs:
  archive_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create archive directory
      run: mkdir archive

    - name: Move files to archive directory
      run: |
        shopt -s extglob
        mv !(archive|.git|link_file.txt) archive/

    - name: Zip the archive directory
      run: zip -r archive.zip archive

    - name: Remove all files except .git and archive.zip
      run: |
        shopt -s extglob
        rm -rf !(archive.zip|.git|link_file.txt)
    - name: Commit archived content
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add archive.zip
        git commit -m "Archived and zipped content"
    