# .github/workflows/archive-and-zip.yml

name: Archive and Zip

on:
  push:
    branches:
      - main

jobs:
  archive_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create archive directory
      run: mkdir archive

    - name: Move files to archive directory
      run: |
        mv !(archive|.git|.github) archive/
    
    - name: Zip the archive directory
      run: zip -r archive.zip archive

    - name: Remove all files except .git and archive.zip
      run: |
        shopt -s extglob
        rm -rf !(archive.zip|.git|.github)

    - name: Connexion
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add archive.zip
        git commit -m "Archive and zip files"
        git push
