

name: Archive and Zip

on:
  push:
    branches:
      - main

jobs:
  archive_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create archive directory
      run: mkdir archive

    - name: Move files to archive directory
      run: |
        mv !(archive|.git|.github) archive/
  
